### ISSUE TITLE
Gostaria de ajudar, mas não sei como fazer.

### ISSUE THREAD

**Issue by ElizaIsADev** [lih-90/escritores-brasileiros.alura#1]
Olá, Aline, tudo bem? Gostei do seu projeto, mas vi que o site, a parte superior, não está sendo exibida corretamente e gostaria de saber como eu posso te ajudar, é só ir ao código e editar? (desculpa, é que eu sou leiga ainda :/ ). Bom, de qlqr forma vou deixar a minha dica aqui, pois o meu site estava igual ao seu (com a parte superior pela metade) eu consegui consertar lá no CSS, deixei o _height_ no _auto_ e funcionou:

`body {
    font-family: "Signika Negative", sans-serif;
    background-image: url("aprendendo-a-ler.png");
    display:flex;
    flex-direction:column;
    align-items: center;
    justify-content: center; 
    **height: auto;** 
    margin: 0; 
    padding: 0; 
}`

Ah, e o _footer_ eu retirei a parte do _position_ daí ele ficou fixado no final da página. Bom, espero ter ajudado de alguma forma ✌️

**Comment by lih-90** [comment]
Olá, Eliza! Primeiro, fico feliz que tenha gostado do meu projeto. Esse foi o meu primeiro, então também estou ainda aprendendo.
Obrigada pelas dicas, tentarei isso! 😄

**Comment by lih-90** [comment]
Consegui mudar.
Muito obrigada!
